### PR TITLE
Ensure clean before env setup

### PR DESCRIPTION
**Pull request by mkth1**

### CODE REVIEW

**Comment by nordixinfra** [comment]
Can one of the admins verify this patch?

**Review by nordixinfra — COMMENTED** [review]
:revolving_hearts: Test pending : https://jenkins.nordix.org/job/airship_nordix_metal3_dev_env_integration_test_ubuntu/4/

**Review by nordixinfra — COMMENTED** [review]
:green_heart: Test Success : https://jenkins.nordix.org/job/airship_nordix_metal3_dev_env_integration_test_ubuntu/4/

**Review by Xenwar — DISMISSED** [review]

**Review by maelk — DISMISSED** [review]

**Review by nordixinfra — COMMENTED** [review]
:revolving_hearts: Ubuntu Test pending : https://jenkins.nordix.org/job/airship_nordix_metal3_dev_env_integration_test_ubuntu/6/

**Review by nordixinfra — COMMENTED** [review]
:green_heart: Test Success Ubuntu : https://jenkins.nordix.org/job/airship_nordix_metal3_dev_env_integration_test_ubuntu/6/

**Pull request closed without merging**
